name: CI

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: .\build.ps1 --target Build
      - name: Publish
        run: .\build.ps1 --target Publish
