name: CI

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: |
          dotnet publish `
            --configuration Release `
            --self-contained true `
            --runtime win-x64 `
            -p:PublishSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:EnableCompressionInSingleFile=true
